# -*- coding: utf-8 -*-
"""projet pyxel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bTfb7p2o_Ghjx4mqtlLadvMznGOO3aFl
"""

import pyxel
import random

class Personnages:
    def __init__(self, nb_ennemis, vie_ennemis=10):
        self.joueur_x = 120
        self.joueur_y = 376
        self.scroll_y = 0
        self.vies_joueur = [[3, 3, 3]]
        self.tirs_joueur = []
        self.tirs_ennemis = []
        self.niveau_termine = False
        self.collision_active = False
        self.invincible = 0

        self.enemies = [{"x": random.randint(0, 208),
                        "y": random.randint(10, 370),
                        "vie": vie_ennemis,
                        "direction": random.choice([-1, 1]),
                        "tir_delai": 0}
                       for _ in range(nb_ennemis)]

    def deplacement_joueur(self):
        if pyxel.btn(pyxel.KEY_Q):
            self.joueur_x = max(self.joueur_x - 3, 0)
        if pyxel.btn(pyxel.KEY_D):
            self.joueur_x = min(self.joueur_x + 3, 224)

    def deplacement_ennemis(self):
        for enemy in self.enemies:
            enemy["x"] += enemy["direction"] * 2
            if enemy["x"] < 0 or enemy["x"] > 208:
                enemy["direction"] *= -1

    def collision_joueur_ennemi(self):
        if self.invincible > 0:
            return False

        for enemy in self.enemies:
            if (self.joueur_x < enemy["x"] + 32 and
                self.joueur_x + 24 > enemy["x"] and
                self.joueur_y < enemy["y"] + 32 and
                self.joueur_y + 24 > enemy["y"]):
                if not self.collision_active:
                    self.collision_active = True
                    return True
                else:
                    return False
        self.collision_active = False
        return False

    def perdre_vie_partielle(self):
        if not self.vies_joueur:
            return True

        for vie in self.vies_joueur:
            for i in range(len(vie)):
                if vie[i] > 0:
                    vie[i] -= 1
                    if sum(vie) == 0:
                        self.vies_joueur.remove(vie)
                    return not self.vies_joueur
        return True

    def update(self):
        if not self.vies_joueur:
            return

        if self.niveau_termine:
            return

        self.invincible = max(0, self.invincible - 1)

        self.deplacement_joueur()
        self.deplacement_ennemis()
        self.scroll_y += 1

        if self.joueur_y > 0:
            self.joueur_y -= 1
        if self.joueur_y == 0:
            self.joueur_y = 376

        for tir in self.tirs_joueur[:]:
            tir["y"] += 5
            if tir["y"] > 400:
                self.tirs_joueur.remove(tir)
                continue

            for enemy in self.enemies[:]:
                if self.collision_tir_ennemi(tir, enemy):
                    enemy["vie"] -= 1
                    self.tirs_joueur.remove(tir)
                    if enemy["vie"] <= 0:
                        self.enemies.remove(enemy)
                        if not self.enemies:
                            self.niveau_termine = True
                    break

        for tir in self.tirs_ennemis[:]:
            tir["y"] -= 3
            if tir["y"] < 0:
                self.tirs_ennemis.remove(tir)
            elif self.collision_tir_joueur(tir):
                self.tirs_ennemis.remove(tir)
                if self.perdre_vie_partielle():
                    return

        for enemy in self.enemies:
            enemy["tir_delai"] += 1
            if enemy["tir_delai"] >= 60:
                self.tirs_ennemis.append({"x": enemy["x"] + 20, "y": enemy["y"]})
                enemy["tir_delai"] = 0

        if self.collision_joueur_ennemi():
            if self.perdre_vie_partielle():
                return

    def collision_tir_ennemi(self, tir, enemy):
        return (tir["x"] < enemy["x"] + 40 and
                tir["x"] + 4 > enemy["x"] and
                tir["y"] < enemy["y"] + 40 and
                tir["y"] + 8 > enemy["y"])

    def collision_tir_joueur(self, tir):
        return (tir["x"] < self.joueur_x + 32 and
                tir["x"] + 4 > self.joueur_x and
                tir["y"] < self.joueur_y + 32 and
                tir["y"] + 8 > self.joueur_y)

    def draw(self):
        pyxel.cls(12)

        if self.invincible == 0 or pyxel.frame_count % 10 < 5:
            pyxel.rect(self.joueur_x, self.joueur_y, 24, 24, 1)

        for enemy in self.enemies:
            pyxel.rect(enemy["x"], enemy["y"], 32, 32, 8)
        for tir in self.tirs_joueur:
            pyxel.rect(tir["x"], tir["y"], 4, 8, 9)
        for tir in self.tirs_ennemis:
            pyxel.rect(tir["x"], tir["y"], 4, 8, 10)

        for i, vie in enumerate(self.vies_joueur):
            for j, part in enumerate(vie):
                color = 8 if part > 0 else 1
                pyxel.rect(10 + j * 6, 10 + i * 8, 4, 4, color)

class Jeu:
    def __init__(self):
        pyxel.init(248, 400, title="One Piece Marine")
        self.difficulte_index = None
        self.menu_actif = True
        self.personnages = None
        self.niveau_1_termine = False
        self.niveau_2_termine = False
        self.niveau_3_termine = False
        self.niveau_perdu = False
        self.bateau_marine_x = 120
        self.bateau_marine_y = 8
        self.niveau_actuel = 1
        self.vies_joueur = [[3, 3, 3]]

        self.difficultes = [
            ('Débutant', 2, 10, 2, 10, 1200, 10, 40),
            ('Intermédiaire', 3, 15, 3, 15, 2400, 20, 50),
            ('Senior', 5, 20, 4, 20, 3600, 30, 60),
            ('Expert', 7, 25, 5, 25, 4800, 40, 70)
        ]

        pyxel.run(self.update, self.draw)

    def update(self):
        if self.menu_actif:
            if pyxel.btnp(pyxel.KEY_1):
                self.difficulte_index = 0
                self.menu_actif = False
                self.personnages = Personnages(self.difficultes[0][1], self.difficultes[0][2])
                self.niveau_1_termine = False
                self.niveau_perdu = False
                self.niveau_actuel = 1
                self.vies_joueur = [[3, 3, 3]]
            elif pyxel.btnp(pyxel.KEY_2):
                self.difficulte_index = 1
                self.menu_actif = False
                self.personnages = Personnages(self.difficultes[1][1], self.difficultes[1][2])
                self.niveau_1_termine = False
                self.niveau_perdu = False
                self.niveau_actuel = 1
                self.vies_joueur = [[3, 3, 3]]
            elif pyxel.btnp(pyxel.KEY_3):
                self.difficulte_index = 2
                self.menu_actif = False
                self.personnages = Personnages(self.difficultes[2][1], self.difficultes[2][2])
                self.niveau_1_termine = False
                self.niveau_perdu = False
                self.niveau_actuel = 1
                self.vies_joueur = [[3, 3, 3]]
            elif pyxel.btnp(pyxel.KEY_4):
                self.difficulte_index = 3
                self.menu_actif = False
                self.personnages = Personnages(self.difficultes[3][1], self.difficultes[3][2])
                self.niveau_1_termine = False
                self.niveau_perdu = False
                self.niveau_actuel = 1
                self.vies_joueur = [[3, 3, 3]]
        else:
            if pyxel.btnp(pyxel.KEY_R):
                self.menu_actif = True
                self.difficulte_index = None
                self.personnages = None
                self.niveau_actuel = 1
                self.vies_joueur = [[3, 3, 3]]
                self.niveau_1_termine = False
                self.niveau_2_termine = False
                self.niveau_3_termine = False
                self.niveau_perdu = False
                return

            if self.niveau_perdu:
                return

            if pyxel.btnp(pyxel.KEY_C):
                if self.niveau_actuel == 1 and self.niveau_1_termine:
                    self.niveau2()
                    self.niveau_actuel = 2
                    self.niveau_1_termine = False
                    self.vies_joueur = [[3, 3, 3]]
                elif self.niveau_actuel == 2 and self.niveau_2_termine:
                    self.niveau3()
                    self.niveau_actuel = 3
                    self.niveau_2_termine = False
                    self.vies_joueur = [[3, 3, 3]]

            if not (self.niveau_1_termine or self.niveau_2_termine or self.niveau_3_termine or self.niveau_perdu):
                if self.niveau_actuel == 1:
                    self.update_niveau1()
                elif self.niveau_actuel == 2:
                    self.update_niveau2()
                elif self.niveau_actuel == 3:
                    self.update_niveau3()

    def update_niveau1(self):
        if not self.vies_joueur:
            self.niveau_perdu = True
            return

        self.personnages.update()

        if not self.personnages.vies_joueur:
            self.niveau_perdu = True
        elif not self.niveau_1_termine:
            self.niveau_1_termine = self.niv_1()

    def niv_1(self):
        return (
            self.personnages.joueur_x < self.bateau_marine_x + 8 and
            self.personnages.joueur_x + 24 > self.bateau_marine_x and
            self.personnages.joueur_y < self.bateau_marine_y + 8 and
            self.personnages.joueur_y + 24 > self.bateau_marine_y
        )

    def niveau2(self):
        self.joueur_x = 120
        self.joueur_y = 100
        self.vies_joueur = [[3, 3, 3]]
        self.invincible = 0

        nb_ennemis = self.difficultes[self.difficulte_index][3]
        vie_ennemis = self.difficultes[self.difficulte_index][4]

        self.niveau2_enemies = [
            {"x": random.randint(0, 208), "y": random.randint(200, 300),
             "vie": vie_ennemis, "direction": random.choice([-1, 1]), "tir_delai": 0}
            for _ in range(nb_ennemis)
        ]

        self.niveau2_tirs_joueur = []
        self.niveau2_tirs_ennemis = []
        self.niveau_2_termine = False
        self.niveau_perdu = False
        self.collision_active = False
        self.timer_victoire = 0

    def update_niveau2(self):
        if not self.vies_joueur:
            self.niveau_perdu = True
            return

        self.invincible = max(0, self.invincible - 1)

        if pyxel.btn(pyxel.KEY_Q):
            self.joueur_x = max(self.joueur_x - 3, 0)
        if pyxel.btn(pyxel.KEY_D):
            self.joueur_x = min(self.joueur_x + 3, 232)

        for enemy in self.niveau2_enemies:
            enemy["x"] += enemy["direction"] * 2
            if enemy["x"] < 0 or enemy["x"] > 208:
                enemy["direction"] *= -1

        if pyxel.btnp(pyxel.KEY_SPACE):
            self.niveau2_tirs_joueur.append({
                "x": self.joueur_x + 16,
                "y": self.joueur_y + 32
            })

        for tir in self.niveau2_tirs_joueur[:]:
            tir["y"] += 5
            if tir["y"] > 400:
                self.niveau2_tirs_joueur.remove(tir)
                continue

            for enemy in self.niveau2_enemies[:]:
                if (tir["x"] < enemy["x"] + 40 and tir["x"] + 4 > enemy["x"] and
                    tir["y"] < enemy["y"] + 40 and tir["y"] + 8 > enemy["y"]):
                    enemy["vie"] -= 1
                    self.niveau2_tirs_joueur.remove(tir)
                    if enemy["vie"] <= 0:
                        self.niveau2_enemies.remove(enemy)
                    break

        for tir in self.niveau2_tirs_ennemis[:]:
            tir["y"] -= 3
            if tir["y"] < 0:
                self.niveau2_tirs_ennemis.remove(tir)
            elif (tir["x"] < self.joueur_x + 32 and tir["x"] + 4 > self.joueur_x and
                  tir["y"] < self.joueur_y + 32 and tir["y"] + 8 > self.joueur_y):
                self.niveau2_tirs_ennemis.remove(tir)
                if self.invincible == 0:
                    if self.perdre_vie_partielle():
                        self.niveau_perdu = True
                    self.invincible = 30

        for enemy in self.niveau2_enemies:
            enemy["tir_delai"] += 1
            if enemy["tir_delai"] >= 60:
                self.niveau2_tirs_ennemis.append({"x": enemy["x"] + 20, "y": enemy["y"]})
                enemy["tir_delai"] = 0

        for enemy in self.niveau2_enemies:
            if (self.invincible == 0 and
                self.joueur_x < enemy["x"] + 40 and self.joueur_x + 32 > enemy["x"] and
                self.joueur_y < enemy["y"] + 40 and self.joueur_y + 32 > enemy["y"]):
                if not self.collision_active:
                    self.collision_active = True
                    if self.perdre_vie_partielle():
                        self.niveau_perdu = True
                    self.invincible = 30
            else:
                self.collision_active = False
        
        if not self.niveau2_enemies:
            self.timer_victoire += 1
            if self.timer_victoire > 60:
                self.niveau_2_termine = True

    def niveau3(self):
        self.joueur_x = 120
        self.joueur_y = 350
        self.vies_joueur = [[3, 3, 3]]
        self.invincible = 0

        duree = self.difficultes[self.difficulte_index][5]
        nb_flaques = self.difficultes[self.difficulte_index][6]
        nb_monstres = self.difficultes[self.difficulte_index][7]

        self.porte_y = -duree
        self.scroll_y_n3 = 0
        self.flaques = [{"x": random.randint(0, 248),
                       "y": random.randint(100, 300),
                       "couleur": random.choice([9, 10, 11])}
                       for _ in range(nb_flaques)]

        self.monstres = []
        self.niveau_3_termine = False
        self.niveau_perdu = False
        self.monstres_restants = nb_monstres
        self.collision_active = False

    def update_niveau3(self):
        if not self.vies_joueur:
            self.niveau_perdu = True
            return

        self.invincible = max(0, self.invincible - 1)
        self.scroll_y_n3 += 1

        if pyxel.btn(pyxel.KEY_Z):
            self.joueur_y = max(self.joueur_y - 2, 0)
        if pyxel.btn(pyxel.KEY_S):
            self.joueur_y = min(self.joueur_y + 2, 368)
        if pyxel.btn(pyxel.KEY_Q):
            self.joueur_x = max(self.joueur_x - 2, 0)
        if pyxel.btn(pyxel.KEY_D):
            self.joueur_x = min(self.joueur_x + 2, 224)

        if (pyxel.frame_count % 30 == 0 and
            self.monstres_restants > 0 and
            len(self.monstres) < 5 + self.difficulte_index * 2):
            self.monstres.append({
                "x": random.randint(0, 224),
                "y": 0,
                "speed_x": random.choice([-1, 0, 1]),
                "speed_y": 1 + self.difficulte_index * 0.5
            })
            self.monstres_restants -= 1

        for monstre in self.monstres[:]:
            monstre["x"] += monstre["speed_x"]
            monstre["y"] += monstre["speed_y"]

            if monstre["x"] < 0 or monstre["x"] > 224:
                monstre["speed_x"] *= -1

            if monstre["y"] > 400:
                self.monstres.remove(monstre)

            if (self.invincible == 0 and
                abs(monstre["x"] - self.joueur_x) < 24 and
                abs(monstre["y"] - self.joueur_y) < 24):
                if not self.collision_active:
                    self.collision_active = True
                    if self.perdre_vie_partielle():
                        self.niveau_perdu = True
                    self.invincible = 30
            else:
                self.collision_active = False

        if self.invincible == 0:
            for flaque in self.flaques[:]:
                if (abs(flaque["x"] - self.joueur_x) < 32 and
                    abs(flaque["y"] - self.joueur_y) < 32):
                    if not self.collision_active:
                        self.collision_active = True
                        if self.perdre_vie_partielle():
                            self.niveau_perdu = True
                        self.flaques.remove(flaque)
                        self.invincible = 30
                    break

        if self.scroll_y_n3 >= self.difficultes[self.difficulte_index][5]:
            self.niveau_3_termine = True

    def perdre_vie_partielle(self):
        if not self.vies_joueur:
            return True

        for vie in self.vies_joueur:
            for i in range(len(vie)):
                if vie[i] > 0:
                    vie[i] -= 1
                    if sum(vie) == 0:
                        self.vies_joueur.remove(vie)
                    return not self.vies_joueur
        return True

    def draw(self):
        if self.menu_actif:
            pyxel.cls(0)
            pyxel.text(50, 100, "Choisissez votre niveau de difficulte :", 7)
            for i, (nom, *_) in enumerate(self.difficultes):
                pyxel.text(70, 150 + i * 10, f"{i+1} - {nom}", 10)

        elif self.niveau_perdu:
            pyxel.cls(0)
            pyxel.text(80, 180, "GAME OVER", 8)
            pyxel.text(80, 190, "Appuyez sur R pour revenir au menu", 5)

        elif self.niveau_1_termine and self.niveau_actuel == 1:
            pyxel.cls(0)
            pyxel.text(80, 180, "NIVEAU 1 REUSSI!", 8)
            pyxel.text(70, 190, "Appuyez sur C pour continuer", 7)
            pyxel.text(70, 200, "Appuyez sur R pour revenir au menu", 5)

        elif self.niveau_2_termine and self.niveau_actuel == 2:
            pyxel.cls(0)
            pyxel.text(80, 180, "NIVEAU 2 REUSSI!", 8)
            pyxel.text(70, 190, "Appuyez sur C pour continuer", 7)
            pyxel.text(70, 200, "Appuyez sur R pour revenir au menu", 5)

        elif self.niveau_3_termine and self.niveau_actuel == 3:
            pyxel.cls(0)
            pyxel.text(80, 180, "GG", 11)
            pyxel.text(70, 190, "Appuyez sur R pour revenir au menu", 5)

        elif self.niveau_actuel == 1:
            self.personnages.draw()
            pyxel.rect(self.bateau_marine_x, self.bateau_marine_y, 8, 8, 8)

        elif self.niveau_actuel == 2:
            pyxel.cls(12)

            if self.invincible == 0 or pyxel.frame_count % 10 < 5:
                pyxel.rect(self.joueur_x, self.joueur_y, 32, 32, 1)

            for enemy in self.niveau2_enemies:
                pyxel.rect(enemy["x"], enemy["y"], 40, 40, 8)
            for tir in self.niveau2_tirs_joueur:
                pyxel.rect(tir["x"], tir["y"], 4, 8, 9)
            for tir in self.niveau2_tirs_ennemis:
                pyxel.rect(tir["x"], tir["y"], 4, 8, 10)

            for i, vie in enumerate(self.vies_joueur):
                for j, part in enumerate(vie):
                    color = 8 if part > 0 else 1
                    pyxel.rect(10 + j * 6, 10 + i * 8, 4, 4, color)

        elif self.niveau_actuel == 3:
            pyxel.cls(12)

            duree = self.difficultes[self.difficulte_index][5]
            pyxel.rect(80, self.porte_y + self.scroll_y_n3, 88, 200, 7)

            progression = min(self.scroll_y_n3 / duree, 1.0)
            pyxel.rect(10, 380, 228, 8, 1)
            pyxel.rect(10, 380, int(228 * progression), 8, 8)

            if self.invincible == 0 or pyxel.frame_count % 10 < 5:
                pyxel.rect(self.joueur_x, self.joueur_y, 32, 32, 8)

            for flaque in self.flaques:
                pyxel.circ(flaque["x"], flaque["y"], 16, flaque["couleur"])

            for monstre in self.monstres:
                taille = 16 + self.difficulte_index * 4
                pyxel.rect(monstre["x"], monstre["y"], taille, taille, 8)

            for i, vie in enumerate(self.vies_joueur):
                for j, part in enumerate(vie):
                    color = 8 if part > 0 else 1
                    pyxel.rect(10 + j * 6, 10 + i * 8, 4, 4, color)

Jeu()

"""
